name: mixin_note
description: Notes with todos.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  flutter_bloc: ^8.0.1
  #firebase
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.10
  google_sign_in: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner:

flutter:
  uses-material-design: true
